### ISSUE TITLE
Add flush method to empty the `logs` array in logger

### ISSUE THREAD

**Issue by BioPhoton** [poppinss/cliui#15]
When testing there is no way to reset the logs in a test

We have to reuse one instance across packages like this `ui().logger`. UI is a singleton and always carries all logs also from previous tests.

**Comment by thetutlage** [comment]
Can you please open a PR for the same?

**Comment by BioPhoton** [comment]
Hi! Ca try to squeeze that in in the next week.

**Comment by BioPhoton** [comment]
Done!
https://github.com/poppinss/cliui/pull/16
