### ISSUE TITLE
Dependency version pins create a conflict

### ISSUE THREAD

**Issue by irskep** [poppinss/cliui#20]
### Package version

6.4.1

### Describe the bug

If I `yarn add @poppinss/cliui` and then try to `import { cliui } from "@poppinss/cliui"`, I get an error:

```
file:///.../node_modules/log-update/node_modules/slice-ansi/index.js:13
	endCodesSet.add(ansiStyles.color.ansi(end));
	                                 ^

TypeError: ansiStyles.color.ansi is not a function
    at file:///.../node_modules/log-update/node_modules/slice-ansi/index.js:13:35
    at ModuleJob.run (node:internal/modules/esm/module_job:218:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:329:24)
    at async loadESM (node:internal/process/esm_loader:34:7)
    at async handleMainPromise (node:internal/modules/run_main:113:12)
```

If I then `yarn install slice-ansi ansi-styles`, the problem goes away. So I think maybe you need to pin the version of one of those packages more specifically. I ended up with `ansi-styles@6.2.1` and `slice-ansi@7.1.0`.

**Comment by RomainLanz** [comment]
Hey @irskep! 👋🏻 

I am not able to reproduce the issue.
Could you please create a repository with the minimum amount of code to reproduce your issue?
